### ISSUE TITLE
Minor typos detected by codespell

### ISSUE THREAD

**Issue by Arsenic-ATG** [Rellotscrewdriver/Math-Loop-Quiz-Program#5]
Math-Loop-Quiz-Program/include.h:58: wether ==> whether

https://github.com/Rellotscrewdriver/Math-Loop-Quiz-Program/blob/c9cc1cf7d137fa6c0ee1e6c2378009b7f185a9df/include.h#L58

---

Math-Loop-Quiz-Program/display.cpp:45: invaild ==> invalid

https://github.com/Rellotscrewdriver/Math-Loop-Quiz-Program/blob/c9cc1cf7d137fa6c0ee1e6c2378009b7f185a9df/display.cpp#L45

**Comment by Rellotscrewdriver** [comment]
Thank you! your requested changes were implemented
